const crypto = require('crypto');

/**
 * The oauth_nonce parameter is a unique token your application should generate
 * for each unique request. Twitter will use this value to determine whether a
 * request has been submitted multiple times.
 *
 * @return string The value for this request was generated by base64
 * encoding 32 bytes of random data, and stripping out all non-word characters
 */
module.exports = () => {
  return crypto.randomBytes(32).toString('hex').substr(0, 32);
};
